/*
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
