/**
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Column Transformation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.up.fe.els2023.dsl.AddColumnTransformation#getColumn <em>Column</em>}</li>
 *   <li>{@link pt.up.fe.els2023.dsl.AddColumnTransformation#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see pt.up.fe.els2023.dsl.DslPackage#getAddColumnTransformation()
 * @model
 * @generated
 */
public interface AddColumnTransformation extends ColumnTransformation
{
  /**
   * Returns the value of the '<em><b>Column</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column</em>' attribute.
   * @see #setColumn(String)
   * @see pt.up.fe.els2023.dsl.DslPackage#getAddColumnTransformation_Column()
   * @model
   * @generated
   */
  String getColumn();

  /**
   * Sets the value of the '{@link pt.up.fe.els2023.dsl.AddColumnTransformation#getColumn <em>Column</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column</em>' attribute.
   * @see #getColumn()
   * @generated
   */
  void setColumn(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see pt.up.fe.els2023.dsl.DslPackage#getAddColumnTransformation_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link pt.up.fe.els2023.dsl.AddColumnTransformation#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // AddColumnTransformation
