/**
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Combination Operations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.up.fe.els2023.dsl.CombinationOperations#getOperation <em>Operation</em>}</li>
 *   <li>{@link pt.up.fe.els2023.dsl.CombinationOperations#getType <em>Type</em>}</li>
 *   <li>{@link pt.up.fe.els2023.dsl.CombinationOperations#getTableOperation <em>Table Operation</em>}</li>
 * </ul>
 *
 * @see pt.up.fe.els2023.dsl.DslPackage#getCombinationOperations()
 * @model
 * @generated
 */
public interface CombinationOperations extends EObject
{
  /**
   * Returns the value of the '<em><b>Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' attribute.
   * @see #setOperation(String)
   * @see pt.up.fe.els2023.dsl.DslPackage#getCombinationOperations_Operation()
   * @model
   * @generated
   */
  String getOperation();

  /**
   * Sets the value of the '{@link pt.up.fe.els2023.dsl.CombinationOperations#getOperation <em>Operation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation</em>' attribute.
   * @see #getOperation()
   * @generated
   */
  void setOperation(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see pt.up.fe.els2023.dsl.DslPackage#getCombinationOperations_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link pt.up.fe.els2023.dsl.CombinationOperations#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Table Operation</b></em>' containment reference list.
   * The list contents are of type {@link pt.up.fe.els2023.dsl.TableOperations}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table Operation</em>' containment reference list.
   * @see pt.up.fe.els2023.dsl.DslPackage#getCombinationOperations_TableOperation()
   * @model containment="true"
   * @generated
   */
  EList<TableOperations> getTableOperation();

} // CombinationOperations
