/**
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fold Sum Tranformation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see pt.up.fe.els2023.dsl.DslPackage#getFoldSumTranformation()
 * @model
 * @generated
 */
public interface FoldSumTranformation extends EObject
{
} // FoldSumTranformation
