/**
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fold Transformation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.up.fe.els2023.dsl.FoldTransformation#getOperation <em>Operation</em>}</li>
 *   <li>{@link pt.up.fe.els2023.dsl.FoldTransformation#getGroupBy <em>Group By</em>}</li>
 * </ul>
 *
 * @see pt.up.fe.els2023.dsl.DslPackage#getFoldTransformation()
 * @model
 * @generated
 */
public interface FoldTransformation extends Transformation
{
  /**
   * Returns the value of the '<em><b>Operation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' containment reference.
   * @see #setOperation(EObject)
   * @see pt.up.fe.els2023.dsl.DslPackage#getFoldTransformation_Operation()
   * @model containment="true"
   * @generated
   */
  EObject getOperation();

  /**
   * Sets the value of the '{@link pt.up.fe.els2023.dsl.FoldTransformation#getOperation <em>Operation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation</em>' containment reference.
   * @see #getOperation()
   * @generated
   */
  void setOperation(EObject value);

  /**
   * Returns the value of the '<em><b>Group By</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Group By</em>' containment reference.
   * @see #setGroupBy(GroupBy)
   * @see pt.up.fe.els2023.dsl.DslPackage#getFoldTransformation_GroupBy()
   * @model containment="true"
   * @generated
   */
  GroupBy getGroupBy();

  /**
   * Sets the value of the '{@link pt.up.fe.els2023.dsl.FoldTransformation#getGroupBy <em>Group By</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Group By</em>' containment reference.
   * @see #getGroupBy()
   * @generated
   */
  void setGroupBy(GroupBy value);

} // FoldTransformation
