/**
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Html Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.up.fe.els2023.dsl.HtmlType#getCssPath <em>Css Path</em>}</li>
 * </ul>
 *
 * @see pt.up.fe.els2023.dsl.DslPackage#getHtmlType()
 * @model
 * @generated
 */
public interface HtmlType extends EObject
{
  /**
   * Returns the value of the '<em><b>Css Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Css Path</em>' attribute.
   * @see #setCssPath(String)
   * @see pt.up.fe.els2023.dsl.DslPackage#getHtmlType_CssPath()
   * @model
   * @generated
   */
  String getCssPath();

  /**
   * Sets the value of the '{@link pt.up.fe.els2023.dsl.HtmlType#getCssPath <em>Css Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Css Path</em>' attribute.
   * @see #getCssPath()
   * @generated
   */
  void setCssPath(String value);

} // HtmlType
