/**
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see pt.up.fe.els2023.dsl.DslPackage#getInputType()
 * @model
 * @generated
 */
public interface InputType extends EObject
{
} // InputType
