/**
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Path Transformation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.up.fe.els2023.dsl.PathTransformation#getOperation <em>Operation</em>}</li>
 *   <li>{@link pt.up.fe.els2023.dsl.PathTransformation#getColumn <em>Column</em>}</li>
 * </ul>
 *
 * @see pt.up.fe.els2023.dsl.DslPackage#getPathTransformation()
 * @model
 * @generated
 */
public interface PathTransformation extends Transformation
{
  /**
   * Returns the value of the '<em><b>Operation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' containment reference.
   * @see #setOperation(EObject)
   * @see pt.up.fe.els2023.dsl.DslPackage#getPathTransformation_Operation()
   * @model containment="true"
   * @generated
   */
  EObject getOperation();

  /**
   * Sets the value of the '{@link pt.up.fe.els2023.dsl.PathTransformation#getOperation <em>Operation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation</em>' containment reference.
   * @see #getOperation()
   * @generated
   */
  void setOperation(EObject value);

  /**
   * Returns the value of the '<em><b>Column</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column</em>' attribute.
   * @see #setColumn(String)
   * @see pt.up.fe.els2023.dsl.DslPackage#getPathTransformation_Column()
   * @model
   * @generated
   */
  String getColumn();

  /**
   * Sets the value of the '{@link pt.up.fe.els2023.dsl.PathTransformation#getColumn <em>Column</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column</em>' attribute.
   * @see #getColumn()
   * @generated
   */
  void setColumn(String value);

} // PathTransformation
