/**
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rename Column Transformation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.up.fe.els2023.dsl.RenameColumnTransformation#getRegex <em>Regex</em>}</li>
 *   <li>{@link pt.up.fe.els2023.dsl.RenameColumnTransformation#getFrom <em>From</em>}</li>
 *   <li>{@link pt.up.fe.els2023.dsl.RenameColumnTransformation#getTo <em>To</em>}</li>
 * </ul>
 *
 * @see pt.up.fe.els2023.dsl.DslPackage#getRenameColumnTransformation()
 * @model
 * @generated
 */
public interface RenameColumnTransformation extends ColumnTransformation
{
  /**
   * Returns the value of the '<em><b>Regex</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Regex</em>' attribute.
   * @see #setRegex(String)
   * @see pt.up.fe.els2023.dsl.DslPackage#getRenameColumnTransformation_Regex()
   * @model
   * @generated
   */
  String getRegex();

  /**
   * Sets the value of the '{@link pt.up.fe.els2023.dsl.RenameColumnTransformation#getRegex <em>Regex</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Regex</em>' attribute.
   * @see #getRegex()
   * @generated
   */
  void setRegex(String value);

  /**
   * Returns the value of the '<em><b>From</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' attribute.
   * @see #setFrom(String)
   * @see pt.up.fe.els2023.dsl.DslPackage#getRenameColumnTransformation_From()
   * @model
   * @generated
   */
  String getFrom();

  /**
   * Sets the value of the '{@link pt.up.fe.els2023.dsl.RenameColumnTransformation#getFrom <em>From</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' attribute.
   * @see #getFrom()
   * @generated
   */
  void setFrom(String value);

  /**
   * Returns the value of the '<em><b>To</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' attribute.
   * @see #setTo(String)
   * @see pt.up.fe.els2023.dsl.DslPackage#getRenameColumnTransformation_To()
   * @model
   * @generated
   */
  String getTo();

  /**
   * Sets the value of the '{@link pt.up.fe.els2023.dsl.RenameColumnTransformation#getTo <em>To</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' attribute.
   * @see #getTo()
   * @generated
   */
  void setTo(String value);

} // RenameColumnTransformation
