/**
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select Rows Transformation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.up.fe.els2023.dsl.SelectRowsTransformation#getStart <em>Start</em>}</li>
 *   <li>{@link pt.up.fe.els2023.dsl.SelectRowsTransformation#getLength <em>Length</em>}</li>
 *   <li>{@link pt.up.fe.els2023.dsl.SelectRowsTransformation#getGroupBy <em>Group By</em>}</li>
 * </ul>
 *
 * @see pt.up.fe.els2023.dsl.DslPackage#getSelectRowsTransformation()
 * @model
 * @generated
 */
public interface SelectRowsTransformation extends RowTransformation
{
  /**
   * Returns the value of the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' attribute.
   * @see #setStart(int)
   * @see pt.up.fe.els2023.dsl.DslPackage#getSelectRowsTransformation_Start()
   * @model
   * @generated
   */
  int getStart();

  /**
   * Sets the value of the '{@link pt.up.fe.els2023.dsl.SelectRowsTransformation#getStart <em>Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' attribute.
   * @see #getStart()
   * @generated
   */
  void setStart(int value);

  /**
   * Returns the value of the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length</em>' attribute.
   * @see #setLength(int)
   * @see pt.up.fe.els2023.dsl.DslPackage#getSelectRowsTransformation_Length()
   * @model
   * @generated
   */
  int getLength();

  /**
   * Sets the value of the '{@link pt.up.fe.els2023.dsl.SelectRowsTransformation#getLength <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length</em>' attribute.
   * @see #getLength()
   * @generated
   */
  void setLength(int value);

  /**
   * Returns the value of the '<em><b>Group By</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Group By</em>' attribute.
   * @see #setGroupBy(String)
   * @see pt.up.fe.els2023.dsl.DslPackage#getSelectRowsTransformation_GroupBy()
   * @model
   * @generated
   */
  String getGroupBy();

  /**
   * Sets the value of the '{@link pt.up.fe.els2023.dsl.SelectRowsTransformation#getGroupBy <em>Group By</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Group By</em>' attribute.
   * @see #getGroupBy()
   * @generated
   */
  void setGroupBy(String value);

} // SelectRowsTransformation
