/**
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transformation Table Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.up.fe.els2023.dsl.TransformationTableOperation#getTransformation <em>Transformation</em>}</li>
 * </ul>
 *
 * @see pt.up.fe.els2023.dsl.DslPackage#getTransformationTableOperation()
 * @model
 * @generated
 */
public interface TransformationTableOperation extends EObject
{
  /**
   * Returns the value of the '<em><b>Transformation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transformation</em>' containment reference.
   * @see #setTransformation(Transformation)
   * @see pt.up.fe.els2023.dsl.DslPackage#getTransformationTableOperation_Transformation()
   * @model containment="true"
   * @generated
   */
  Transformation getTransformation();

  /**
   * Sets the value of the '{@link pt.up.fe.els2023.dsl.TransformationTableOperation#getTransformation <em>Transformation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transformation</em>' containment reference.
   * @see #getTransformation()
   * @generated
   */
  void setTransformation(Transformation value);

} // TransformationTableOperation
