/**
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Yaml Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see pt.up.fe.els2023.dsl.DslPackage#getYamlType()
 * @model
 * @generated
 */
public interface YamlType extends InputType
{
} // YamlType
