/*
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import pt.up.fe.els2023.externalDsl.MyDsl

@ExtendWith(InjectionExtension)
@InjectWith(ExternalDslInjectorProvider)
class ExternalDslParsingTest {
	@Inject
	ParseHelper<MyDsl> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
