/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class MyDslElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MyDsl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPipelinesAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPipelinesPipelineParserRuleCall_0_0 = (RuleCall)cPipelinesAssignment_0.eContents().get(0);
		private final Assignment cSourcesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSourcesSourceParserRuleCall_1_0 = (RuleCall)cSourcesAssignment_1.eContents().get(0);
		private final Assignment cTablesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTablesTableParserRuleCall_2_0 = (RuleCall)cTablesAssignment_2.eContents().get(0);
		private final Assignment cExportAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExportExportParserRuleCall_3_0 = (RuleCall)cExportAssignment_3.eContents().get(0);
		
		//MyDsl:
		//    pipelines += Pipeline*
		//    sources += Source*
		//    tables += Table*
		//    export += Export*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//pipelines += Pipeline*
		//sources += Source*
		//tables += Table*
		//export += Export*
		public Group getGroup() { return cGroup; }
		
		//pipelines += Pipeline*
		public Assignment getPipelinesAssignment_0() { return cPipelinesAssignment_0; }
		
		//Pipeline
		public RuleCall getPipelinesPipelineParserRuleCall_0_0() { return cPipelinesPipelineParserRuleCall_0_0; }
		
		//sources += Source*
		public Assignment getSourcesAssignment_1() { return cSourcesAssignment_1; }
		
		//Source
		public RuleCall getSourcesSourceParserRuleCall_1_0() { return cSourcesSourceParserRuleCall_1_0; }
		
		//tables += Table*
		public Assignment getTablesAssignment_2() { return cTablesAssignment_2; }
		
		//Table
		public RuleCall getTablesTableParserRuleCall_2_0() { return cTablesTableParserRuleCall_2_0; }
		
		//export += Export*
		public Assignment getExportAssignment_3() { return cExportAssignment_3; }
		
		//Export
		public RuleCall getExportExportParserRuleCall_3_0() { return cExportExportParserRuleCall_3_0; }
	}
	public class CombinationOperationsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.CombinationOperations");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cOperationAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Alternatives cOperationAlternatives_0_0 = (Alternatives)cOperationAssignment_0.eContents().get(0);
		private final Keyword cOperationMergeKeyword_0_0_0 = (Keyword)cOperationAlternatives_0_0.eContents().get(0);
		private final Keyword cOperationAppendKeyword_0_0_1 = (Keyword)cOperationAlternatives_0_0.eContents().get(1);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cTypeAlternatives_1_0 = (Alternatives)cTypeAssignment_1.eContents().get(0);
		private final Keyword cTypeUnionKeyword_1_0_0 = (Keyword)cTypeAlternatives_1_0.eContents().get(0);
		private final Keyword cTypeIntersectionKeyword_1_0_1 = (Keyword)cTypeAlternatives_1_0.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTableOperationAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTableOperationTableOperationsParserRuleCall_3_0 = (RuleCall)cTableOperationAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTableOperationAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTableOperationTableOperationsParserRuleCall_4_1_0 = (RuleCall)cTableOperationAssignment_4_1.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cRightSquareBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//CombinationOperations:
		//    operation = ('merge' | 'append') type = ("union" | "intersection")?  "["
		//        tableOperation += TableOperations (',' tableOperation+=TableOperations)* (',')?
		//    "]"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//operation = ('merge' | 'append') type = ("union" | "intersection")?  "["
		//    tableOperation += TableOperations (',' tableOperation+=TableOperations)* (',')?
		//"]"
		public Group getGroup() { return cGroup; }
		
		//operation = ('merge' | 'append')
		public Assignment getOperationAssignment_0() { return cOperationAssignment_0; }
		
		//('merge' | 'append')
		public Alternatives getOperationAlternatives_0_0() { return cOperationAlternatives_0_0; }
		
		//'merge'
		public Keyword getOperationMergeKeyword_0_0_0() { return cOperationMergeKeyword_0_0_0; }
		
		//'append'
		public Keyword getOperationAppendKeyword_0_0_1() { return cOperationAppendKeyword_0_0_1; }
		
		//type = ("union" | "intersection")?
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//("union" | "intersection")
		public Alternatives getTypeAlternatives_1_0() { return cTypeAlternatives_1_0; }
		
		//"union"
		public Keyword getTypeUnionKeyword_1_0_0() { return cTypeUnionKeyword_1_0_0; }
		
		//"intersection"
		public Keyword getTypeIntersectionKeyword_1_0_1() { return cTypeIntersectionKeyword_1_0_1; }
		
		//"["
		public Keyword getLeftSquareBracketKeyword_2() { return cLeftSquareBracketKeyword_2; }
		
		//tableOperation += TableOperations
		public Assignment getTableOperationAssignment_3() { return cTableOperationAssignment_3; }
		
		//TableOperations
		public RuleCall getTableOperationTableOperationsParserRuleCall_3_0() { return cTableOperationTableOperationsParserRuleCall_3_0; }
		
		//(',' tableOperation+=TableOperations)*
		public Group getGroup_4() { return cGroup_4; }
		
		//','
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//tableOperation+=TableOperations
		public Assignment getTableOperationAssignment_4_1() { return cTableOperationAssignment_4_1; }
		
		//TableOperations
		public RuleCall getTableOperationTableOperationsParserRuleCall_4_1_0() { return cTableOperationTableOperationsParserRuleCall_4_1_0; }
		
		//(',')?
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//"]"
		public Keyword getRightSquareBracketKeyword_6() { return cRightSquareBracketKeyword_6; }
	}
	public class TableOperationsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.TableOperations");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCombinationOperationsParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTransformOperationParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSourceOperationParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//TableOperations:
		//    CombinationOperations | TransformOperation    | SourceOperation
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//CombinationOperations | TransformOperation	| SourceOperation
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CombinationOperations
		public RuleCall getCombinationOperationsParserRuleCall_0() { return cCombinationOperationsParserRuleCall_0; }
		
		//TransformOperation
		public RuleCall getTransformOperationParserRuleCall_1() { return cTransformOperationParserRuleCall_1; }
		
		//SourceOperation
		public RuleCall getSourceOperationParserRuleCall_2() { return cSourceOperationParserRuleCall_2; }
	}
	public class SourceOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SourceOperation");
		private final Assignment cSourceAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cSourceIDTerminalRuleCall_0 = (RuleCall)cSourceAssignment.eContents().get(0);
		
		//SourceOperation:
		//    source = ID
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//source = ID
		public Assignment getSourceAssignment() { return cSourceAssignment; }
		
		//ID
		public RuleCall getSourceIDTerminalRuleCall_0() { return cSourceIDTerminalRuleCall_0; }
	}
	public class TransformationTableOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.TransformationTableOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTransformationAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTransformationTransformationParserRuleCall_1_0 = (RuleCall)cTransformationAssignment_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//TransformationTableOperation:
		//    '('transformation = Transformation')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'('transformation = Transformation')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//transformation = Transformation
		public Assignment getTransformationAssignment_1() { return cTransformationAssignment_1; }
		
		//Transformation
		public RuleCall getTransformationTransformationParserRuleCall_1_0() { return cTransformationTransformationParserRuleCall_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}
	public class PipelineTableOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.PipelineTableOperation");
		private final Assignment cPipelineAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cPipelineIDTerminalRuleCall_0 = (RuleCall)cPipelineAssignment.eContents().get(0);
		
		//PipelineTableOperation:
		//    pipeline = ID
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//pipeline = ID
		public Assignment getPipelineAssignment() { return cPipelineAssignment; }
		
		//ID
		public RuleCall getPipelineIDTerminalRuleCall_0() { return cPipelineIDTerminalRuleCall_0; }
	}
	public class TransformOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.TransformOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSourceAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSourceSourceOperationParserRuleCall_0_0 = (RuleCall)cSourceAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cTransformKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cOperationAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cOperationAlternatives_1_1_0 = (Alternatives)cOperationAssignment_1_1.eContents().get(0);
		private final RuleCall cOperationTransformationTableOperationParserRuleCall_1_1_0_0 = (RuleCall)cOperationAlternatives_1_1_0.eContents().get(0);
		private final RuleCall cOperationPipelineTableOperationParserRuleCall_1_1_0_1 = (RuleCall)cOperationAlternatives_1_1_0.eContents().get(1);
		
		//TransformOperation:
		//    source = SourceOperation ('transform' operation += ( TransformationTableOperation | PipelineTableOperation))+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//source = SourceOperation ('transform' operation += ( TransformationTableOperation | PipelineTableOperation))+
		public Group getGroup() { return cGroup; }
		
		//source = SourceOperation
		public Assignment getSourceAssignment_0() { return cSourceAssignment_0; }
		
		//SourceOperation
		public RuleCall getSourceSourceOperationParserRuleCall_0_0() { return cSourceSourceOperationParserRuleCall_0_0; }
		
		//('transform' operation += ( TransformationTableOperation | PipelineTableOperation))+
		public Group getGroup_1() { return cGroup_1; }
		
		//'transform'
		public Keyword getTransformKeyword_1_0() { return cTransformKeyword_1_0; }
		
		//operation += ( TransformationTableOperation | PipelineTableOperation)
		public Assignment getOperationAssignment_1_1() { return cOperationAssignment_1_1; }
		
		//( TransformationTableOperation | PipelineTableOperation)
		public Alternatives getOperationAlternatives_1_1_0() { return cOperationAlternatives_1_1_0; }
		
		//TransformationTableOperation
		public RuleCall getOperationTransformationTableOperationParserRuleCall_1_1_0_0() { return cOperationTransformationTableOperationParserRuleCall_1_1_0_0; }
		
		//PipelineTableOperation
		public RuleCall getOperationPipelineTableOperationParserRuleCall_1_1_0_1() { return cOperationPipelineTableOperationParserRuleCall_1_1_0_1; }
	}
	public class TableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Table");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cOperationAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOperationTableOperationsParserRuleCall_2_0 = (RuleCall)cOperationAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Table:
		//    name=ID '='
		//    operation = TableOperations
		//    ";"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID '='
		//operation = TableOperations
		//";"
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }
		
		//operation = TableOperations
		public Assignment getOperationAssignment_2() { return cOperationAssignment_2; }
		
		//TableOperations
		public RuleCall getOperationTableOperationsParserRuleCall_2_0() { return cOperationTableOperationsParserRuleCall_2_0; }
		
		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class XmlTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.XmlType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXmlTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cXmlKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cXpathKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Keyword cEqualsSignKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Assignment cPathAssignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cPathSTRINGTerminalRuleCall_2_3_0 = (RuleCall)cPathAssignment_2_3.eContents().get(0);
		private final Keyword cCommaKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_2_5 = (Keyword)cGroup_2.eContents().get(5);
		
		//XmlType:
		//    {XmlType} 'xml'( '{' 'xpath' '=' path = STRING ',' "}" )?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{XmlType} 'xml'( '{' 'xpath' '=' path = STRING ',' "}" )?
		public Group getGroup() { return cGroup; }
		
		//{XmlType}
		public Action getXmlTypeAction_0() { return cXmlTypeAction_0; }
		
		//'xml'
		public Keyword getXmlKeyword_1() { return cXmlKeyword_1; }
		
		//( '{' 'xpath' '=' path = STRING ',' "}" )?
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//'xpath'
		public Keyword getXpathKeyword_2_1() { return cXpathKeyword_2_1; }
		
		//'='
		public Keyword getEqualsSignKeyword_2_2() { return cEqualsSignKeyword_2_2; }
		
		//path = STRING
		public Assignment getPathAssignment_2_3() { return cPathAssignment_2_3; }
		
		//STRING
		public RuleCall getPathSTRINGTerminalRuleCall_2_3_0() { return cPathSTRINGTerminalRuleCall_2_3_0; }
		
		//','
		public Keyword getCommaKeyword_2_4() { return cCommaKeyword_2_4; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_2_5() { return cRightCurlyBracketKeyword_2_5; }
	}
	public class JsonTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.JsonType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cJsonTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cJsonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cJsonpathKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Keyword cEqualsSignKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Assignment cPathAssignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cPathSTRINGTerminalRuleCall_2_3_0 = (RuleCall)cPathAssignment_2_3.eContents().get(0);
		private final Keyword cCommaKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_2_5 = (Keyword)cGroup_2.eContents().get(5);
		
		//JsonType:
		//        {JsonType} 'json'( '{' 'jsonpath' '=' path = STRING ',' "}" )?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{JsonType} 'json'( '{' 'jsonpath' '=' path = STRING ',' "}" )?
		public Group getGroup() { return cGroup; }
		
		//{JsonType}
		public Action getJsonTypeAction_0() { return cJsonTypeAction_0; }
		
		//'json'
		public Keyword getJsonKeyword_1() { return cJsonKeyword_1; }
		
		//( '{' 'jsonpath' '=' path = STRING ',' "}" )?
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//'jsonpath'
		public Keyword getJsonpathKeyword_2_1() { return cJsonpathKeyword_2_1; }
		
		//'='
		public Keyword getEqualsSignKeyword_2_2() { return cEqualsSignKeyword_2_2; }
		
		//path = STRING
		public Assignment getPathAssignment_2_3() { return cPathAssignment_2_3; }
		
		//STRING
		public RuleCall getPathSTRINGTerminalRuleCall_2_3_0() { return cPathSTRINGTerminalRuleCall_2_3_0; }
		
		//','
		public Keyword getCommaKeyword_2_4() { return cCommaKeyword_2_4; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_2_5() { return cRightCurlyBracketKeyword_2_5; }
	}
	public class YamlTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.YamlType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cYamlTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cYamlKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//YamlType:
		//        {YamlType} 'yaml'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{YamlType} 'yaml'
		public Group getGroup() { return cGroup; }
		
		//{YamlType}
		public Action getYamlTypeAction_0() { return cYamlTypeAction_0; }
		
		//'yaml'
		public Keyword getYamlKeyword_1() { return cYamlKeyword_1; }
	}
	public class CsvTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.CsvType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCsvTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCsvKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//CsvType:
		//        {CsvType} 'csv'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{CsvType} 'csv'
		public Group getGroup() { return cGroup; }
		
		//{CsvType}
		public Action getCsvTypeAction_0() { return cCsvTypeAction_0; }
		
		//'csv'
		public Keyword getCsvKeyword_1() { return cCsvKeyword_1; }
	}
	public class AutoTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.AutoType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAutoTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAutoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//AutoType:
		//        {AutoType} 'auto'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{AutoType} 'auto'
		public Group getGroup() { return cGroup; }
		
		//{AutoType}
		public Action getAutoTypeAction_0() { return cAutoTypeAction_0; }
		
		//'auto'
		public Keyword getAutoKeyword_1() { return cAutoKeyword_1; }
	}
	public class InputTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.InputType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cJsonTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cXmlTypeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCsvTypeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cYamlTypeParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cAutoTypeParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//InputType:
		//    JsonType | XmlType | CsvType | YamlType | AutoType
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//JsonType | XmlType | CsvType | YamlType | AutoType
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//JsonType
		public RuleCall getJsonTypeParserRuleCall_0() { return cJsonTypeParserRuleCall_0; }
		
		//XmlType
		public RuleCall getXmlTypeParserRuleCall_1() { return cXmlTypeParserRuleCall_1; }
		
		//CsvType
		public RuleCall getCsvTypeParserRuleCall_2() { return cCsvTypeParserRuleCall_2; }
		
		//YamlType
		public RuleCall getYamlTypeParserRuleCall_3() { return cYamlTypeParserRuleCall_3; }
		
		//AutoType
		public RuleCall getAutoTypeParserRuleCall_4() { return cAutoTypeParserRuleCall_4; }
	}
	public class HtmlTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.HtmlType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cHtmlTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cHtmlKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cCssKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Keyword cEqualsSignKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Assignment cCssPathAssignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cCssPathSTRINGTerminalRuleCall_2_3_0 = (RuleCall)cCssPathAssignment_2_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		
		//HtmlType:
		//    {HtmlType} 'html' ('{''css' '=' cssPath = STRING '}')?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{HtmlType} 'html' ('{''css' '=' cssPath = STRING '}')?
		public Group getGroup() { return cGroup; }
		
		//{HtmlType}
		public Action getHtmlTypeAction_0() { return cHtmlTypeAction_0; }
		
		//'html'
		public Keyword getHtmlKeyword_1() { return cHtmlKeyword_1; }
		
		//('{''css' '=' cssPath = STRING '}')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//'css'
		public Keyword getCssKeyword_2_1() { return cCssKeyword_2_1; }
		
		//'='
		public Keyword getEqualsSignKeyword_2_2() { return cEqualsSignKeyword_2_2; }
		
		//cssPath = STRING
		public Assignment getCssPathAssignment_2_3() { return cCssPathAssignment_2_3; }
		
		//STRING
		public RuleCall getCssPathSTRINGTerminalRuleCall_2_3_0() { return cCssPathSTRINGTerminalRuleCall_2_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_4() { return cRightCurlyBracketKeyword_2_4; }
	}
	public class OutputTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.OutputType");
		private final Assignment cTypeAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cTypeAlternatives_0 = (Alternatives)cTypeAssignment.eContents().get(0);
		private final RuleCall cTypeHtmlTypeParserRuleCall_0_0 = (RuleCall)cTypeAlternatives_0.eContents().get(0);
		private final RuleCall cTypeAutoTypeParserRuleCall_0_1 = (RuleCall)cTypeAlternatives_0.eContents().get(1);
		private final RuleCall cTypeCsvTypeParserRuleCall_0_2 = (RuleCall)cTypeAlternatives_0.eContents().get(2);
		
		//OutputType:
		//    type = (HtmlType | AutoType | CsvType )
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//type = (HtmlType | AutoType | CsvType )
		public Assignment getTypeAssignment() { return cTypeAssignment; }
		
		//(HtmlType | AutoType | CsvType )
		public Alternatives getTypeAlternatives_0() { return cTypeAlternatives_0; }
		
		//HtmlType
		public RuleCall getTypeHtmlTypeParserRuleCall_0_0() { return cTypeHtmlTypeParserRuleCall_0_0; }
		
		//AutoType
		public RuleCall getTypeAutoTypeParserRuleCall_0_1() { return cTypeAutoTypeParserRuleCall_0_1; }
		
		//CsvType
		public RuleCall getTypeCsvTypeParserRuleCall_0_2() { return cTypeCsvTypeParserRuleCall_0_2; }
	}
	public class MetaDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MetaData");
		private final Assignment cMetadataAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cMetadataAlternatives_0 = (Alternatives)cMetadataAssignment.eContents().get(0);
		private final Keyword cMetadataFilepathKeyword_0_0 = (Keyword)cMetadataAlternatives_0.eContents().get(0);
		private final Keyword cMetadataLastmodifiedKeyword_0_1 = (Keyword)cMetadataAlternatives_0.eContents().get(1);
		
		//MetaData:
		//    metadata = ('filepath' | 'lastmodified')
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//metadata = ('filepath' | 'lastmodified')
		public Assignment getMetadataAssignment() { return cMetadataAssignment; }
		
		//('filepath' | 'lastmodified')
		public Alternatives getMetadataAlternatives_0() { return cMetadataAlternatives_0; }
		
		//'filepath'
		public Keyword getMetadataFilepathKeyword_0_0() { return cMetadataFilepathKeyword_0_0; }
		
		//'lastmodified'
		public Keyword getMetadataLastmodifiedKeyword_0_1() { return cMetadataLastmodifiedKeyword_0_1; }
	}
	public class SourceStoreElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SourceStore");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStoreKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMetadataAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMetadataMetaDataParserRuleCall_1_0 = (RuleCall)cMetadataAssignment_1.eContents().get(0);
		private final Keyword cInKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cColumnAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cColumnSTRINGTerminalRuleCall_3_0 = (RuleCall)cColumnAssignment_3.eContents().get(0);
		
		//SourceStore:
		//    'store' metadata=MetaData 'in' column = STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'store' metadata=MetaData 'in' column = STRING
		public Group getGroup() { return cGroup; }
		
		//'store'
		public Keyword getStoreKeyword_0() { return cStoreKeyword_0; }
		
		//metadata=MetaData
		public Assignment getMetadataAssignment_1() { return cMetadataAssignment_1; }
		
		//MetaData
		public RuleCall getMetadataMetaDataParserRuleCall_1_0() { return cMetadataMetaDataParserRuleCall_1_0; }
		
		//'in'
		public Keyword getInKeyword_2() { return cInKeyword_2; }
		
		//column = STRING
		public Assignment getColumnAssignment_3() { return cColumnAssignment_3; }
		
		//STRING
		public RuleCall getColumnSTRINGTerminalRuleCall_3_0() { return cColumnSTRINGTerminalRuleCall_3_0; }
	}
	public class SourceCoumnSelectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SourceCoumnSelect");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSelectingKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cColumnAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cColumnSTRINGTerminalRuleCall_2_0 = (RuleCall)cColumnAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cColumnAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cColumnSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cColumnAssignment_3_1.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cRightSquareBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//SourceCoumnSelect:
		//    'selecting' '[' column += STRING (',' column += STRING)* (',')? ']'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'selecting' '[' column += STRING (',' column += STRING)* (',')? ']'
		public Group getGroup() { return cGroup; }
		
		//'selecting'
		public Keyword getSelectingKeyword_0() { return cSelectingKeyword_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }
		
		//column += STRING
		public Assignment getColumnAssignment_2() { return cColumnAssignment_2; }
		
		//STRING
		public RuleCall getColumnSTRINGTerminalRuleCall_2_0() { return cColumnSTRINGTerminalRuleCall_2_0; }
		
		//(',' column += STRING)*
		public Group getGroup_3() { return cGroup_3; }
		
		//','
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//column += STRING
		public Assignment getColumnAssignment_3_1() { return cColumnAssignment_3_1; }
		
		//STRING
		public RuleCall getColumnSTRINGTerminalRuleCall_3_1_0() { return cColumnSTRINGTerminalRuleCall_3_1_0; }
		
		//(',')?
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_5() { return cRightSquareBracketKeyword_5; }
	}
	public class SourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Source");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cImportKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cQueryAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cQuerySTRINGTerminalRuleCall_3_0 = (RuleCall)cQueryAssignment_3.eContents().get(0);
		private final Keyword cFromKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cFilePathAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFilePathSTRINGTerminalRuleCall_5_0 = (RuleCall)cFilePathAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cAsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cInputTypeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cInputTypeInputTypeParserRuleCall_6_1_0 = (RuleCall)cInputTypeAssignment_6_1.eContents().get(0);
		private final Assignment cStoreAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cStoreSourceStoreParserRuleCall_7_0 = (RuleCall)cStoreAssignment_7.eContents().get(0);
		private final Assignment cSelectAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cSelectSourceCoumnSelectParserRuleCall_8_0 = (RuleCall)cSelectAssignment_8.eContents().get(0);
		private final Keyword cSemicolonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Source:
		//    name=ID '=' 'import' (query=STRING)? 'from' filePath=STRING ('as' inputType=InputType)?
		//    store += SourceStore*
		//    select = (SourceCoumnSelect)?
		//    ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID '=' 'import' (query=STRING)? 'from' filePath=STRING ('as' inputType=InputType)?
		//store += SourceStore*
		//select = (SourceCoumnSelect)?
		//';'
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }
		
		//'import'
		public Keyword getImportKeyword_2() { return cImportKeyword_2; }
		
		//(query=STRING)?
		public Assignment getQueryAssignment_3() { return cQueryAssignment_3; }
		
		//STRING
		public RuleCall getQuerySTRINGTerminalRuleCall_3_0() { return cQuerySTRINGTerminalRuleCall_3_0; }
		
		//'from'
		public Keyword getFromKeyword_4() { return cFromKeyword_4; }
		
		//filePath=STRING
		public Assignment getFilePathAssignment_5() { return cFilePathAssignment_5; }
		
		//STRING
		public RuleCall getFilePathSTRINGTerminalRuleCall_5_0() { return cFilePathSTRINGTerminalRuleCall_5_0; }
		
		//('as' inputType=InputType)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'as'
		public Keyword getAsKeyword_6_0() { return cAsKeyword_6_0; }
		
		//inputType=InputType
		public Assignment getInputTypeAssignment_6_1() { return cInputTypeAssignment_6_1; }
		
		//InputType
		public RuleCall getInputTypeInputTypeParserRuleCall_6_1_0() { return cInputTypeInputTypeParserRuleCall_6_1_0; }
		
		//store += SourceStore*
		public Assignment getStoreAssignment_7() { return cStoreAssignment_7; }
		
		//SourceStore
		public RuleCall getStoreSourceStoreParserRuleCall_7_0() { return cStoreSourceStoreParserRuleCall_7_0; }
		
		//select = (SourceCoumnSelect)?
		public Assignment getSelectAssignment_8() { return cSelectAssignment_8; }
		
		//(SourceCoumnSelect)
		public RuleCall getSelectSourceCoumnSelectParserRuleCall_8_0() { return cSelectSourceCoumnSelectParserRuleCall_8_0; }
		
		//';'
		public Keyword getSemicolonKeyword_9() { return cSemicolonKeyword_9; }
	}
	public class CanonicalizePathTransformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.CanonicalizePathTransformation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCanonicalizePathTransformationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCanonicalizeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPathKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//CanonicalizePathTransformation:
		//    {CanonicalizePathTransformation} 'canonicalize' 'path'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{CanonicalizePathTransformation} 'canonicalize' 'path'
		public Group getGroup() { return cGroup; }
		
		//{CanonicalizePathTransformation}
		public Action getCanonicalizePathTransformationAction_0() { return cCanonicalizePathTransformationAction_0; }
		
		//'canonicalize'
		public Keyword getCanonicalizeKeyword_1() { return cCanonicalizeKeyword_1; }
		
		//'path'
		public Keyword getPathKeyword_2() { return cPathKeyword_2; }
	}
	public class GetPathTransformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.GetPathTransformation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cGetPathTransformationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cGetKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPathKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//GetPathTransformation:
		//    {GetPathTransformation} 'get' 'path' 'name'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{GetPathTransformation} 'get' 'path' 'name'
		public Group getGroup() { return cGroup; }
		
		//{GetPathTransformation}
		public Action getGetPathTransformationAction_0() { return cGetPathTransformationAction_0; }
		
		//'get'
		public Keyword getGetKeyword_1() { return cGetKeyword_1; }
		
		//'path'
		public Keyword getPathKeyword_2() { return cPathKeyword_2; }
		
		//'name'
		public Keyword getNameKeyword_3() { return cNameKeyword_3; }
	}
	public class AppendPathTransformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.AppendPathTransformation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAppendKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cPathKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPathAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPathSTRINGTerminalRuleCall_2_0 = (RuleCall)cPathAssignment_2.eContents().get(0);
		
		//AppendPathTransformation:
		//    'append' 'path' path = STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'append' 'path' path = STRING
		public Group getGroup() { return cGroup; }
		
		//'append'
		public Keyword getAppendKeyword_0() { return cAppendKeyword_0; }
		
		//'path'
		public Keyword getPathKeyword_1() { return cPathKeyword_1; }
		
		//path = STRING
		public Assignment getPathAssignment_2() { return cPathAssignment_2; }
		
		//STRING
		public RuleCall getPathSTRINGTerminalRuleCall_2_0() { return cPathSTRINGTerminalRuleCall_2_0; }
	}
	public class PathTransformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.PathTransformation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cColumnAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cColumnSTRINGTerminalRuleCall_1_0 = (RuleCall)cColumnAssignment_1.eContents().get(0);
		private final Assignment cOperationAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cOperationAlternatives_2_0 = (Alternatives)cOperationAssignment_2.eContents().get(0);
		private final RuleCall cOperationAppendPathTransformationParserRuleCall_2_0_0 = (RuleCall)cOperationAlternatives_2_0.eContents().get(0);
		private final RuleCall cOperationCanonicalizePathTransformationParserRuleCall_2_0_1 = (RuleCall)cOperationAlternatives_2_0.eContents().get(1);
		private final RuleCall cOperationGetPathTransformationParserRuleCall_2_0_2 = (RuleCall)cOperationAlternatives_2_0.eContents().get(2);
		
		//PathTransformation:
		//    'in' column = STRING operation = (AppendPathTransformation | CanonicalizePathTransformation | GetPathTransformation)
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'in' column = STRING operation = (AppendPathTransformation | CanonicalizePathTransformation | GetPathTransformation)
		public Group getGroup() { return cGroup; }
		
		//'in'
		public Keyword getInKeyword_0() { return cInKeyword_0; }
		
		//column = STRING
		public Assignment getColumnAssignment_1() { return cColumnAssignment_1; }
		
		//STRING
		public RuleCall getColumnSTRINGTerminalRuleCall_1_0() { return cColumnSTRINGTerminalRuleCall_1_0; }
		
		//operation = (AppendPathTransformation | CanonicalizePathTransformation | GetPathTransformation)
		public Assignment getOperationAssignment_2() { return cOperationAssignment_2; }
		
		//(AppendPathTransformation | CanonicalizePathTransformation | GetPathTransformation)
		public Alternatives getOperationAlternatives_2_0() { return cOperationAlternatives_2_0; }
		
		//AppendPathTransformation
		public RuleCall getOperationAppendPathTransformationParserRuleCall_2_0_0() { return cOperationAppendPathTransformationParserRuleCall_2_0_0; }
		
		//CanonicalizePathTransformation
		public RuleCall getOperationCanonicalizePathTransformationParserRuleCall_2_0_1() { return cOperationCanonicalizePathTransformationParserRuleCall_2_0_1; }
		
		//GetPathTransformation
		public RuleCall getOperationGetPathTransformationParserRuleCall_2_0_2() { return cOperationGetPathTransformationParserRuleCall_2_0_2; }
	}
	public class FoldMaxTranformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.FoldMaxTranformation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cColumnAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cColumnSTRINGTerminalRuleCall_1_0 = (RuleCall)cColumnAssignment_1.eContents().get(0);
		private final Keyword cFoldKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMaxKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//FoldMaxTranformation:
		//    'in' column = STRING 'fold' 'max'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'in' column = STRING 'fold' 'max'
		public Group getGroup() { return cGroup; }
		
		//'in'
		public Keyword getInKeyword_0() { return cInKeyword_0; }
		
		//column = STRING
		public Assignment getColumnAssignment_1() { return cColumnAssignment_1; }
		
		//STRING
		public RuleCall getColumnSTRINGTerminalRuleCall_1_0() { return cColumnSTRINGTerminalRuleCall_1_0; }
		
		//'fold'
		public Keyword getFoldKeyword_2() { return cFoldKeyword_2; }
		
		//'max'
		public Keyword getMaxKeyword_3() { return cMaxKeyword_3; }
	}
	public class FoldAverageTranformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.FoldAverageTranformation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFoldAverageTranformationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFoldKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cAvgKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//FoldAverageTranformation:
		//    {FoldAverageTranformation} 'fold' 'avg'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{FoldAverageTranformation} 'fold' 'avg'
		public Group getGroup() { return cGroup; }
		
		//{FoldAverageTranformation}
		public Action getFoldAverageTranformationAction_0() { return cFoldAverageTranformationAction_0; }
		
		//'fold'
		public Keyword getFoldKeyword_1() { return cFoldKeyword_1; }
		
		//'avg'
		public Keyword getAvgKeyword_2() { return cAvgKeyword_2; }
	}
	public class FoldSumTranformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.FoldSumTranformation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFoldSumTranformationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFoldKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSumKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//FoldSumTranformation:
		//    {FoldSumTranformation} 'fold' 'sum'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{FoldSumTranformation} 'fold' 'sum'
		public Group getGroup() { return cGroup; }
		
		//{FoldSumTranformation}
		public Action getFoldSumTranformationAction_0() { return cFoldSumTranformationAction_0; }
		
		//'fold'
		public Keyword getFoldKeyword_1() { return cFoldKeyword_1; }
		
		//'sum'
		public Keyword getSumKeyword_2() { return cSumKeyword_2; }
	}
	public class GroupByElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.GroupBy");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGroupKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cByKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cColumnAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cColumnSTRINGTerminalRuleCall_2_0 = (RuleCall)cColumnAssignment_2.eContents().get(0);
		
		//GroupBy:
		//    'group' 'by' column = STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'group' 'by' column = STRING
		public Group getGroup() { return cGroup; }
		
		//'group'
		public Keyword getGroupKeyword_0() { return cGroupKeyword_0; }
		
		//'by'
		public Keyword getByKeyword_1() { return cByKeyword_1; }
		
		//column = STRING
		public Assignment getColumnAssignment_2() { return cColumnAssignment_2; }
		
		//STRING
		public RuleCall getColumnSTRINGTerminalRuleCall_2_0() { return cColumnSTRINGTerminalRuleCall_2_0; }
	}
	public class FoldTransformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.FoldTransformation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cOperationAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Alternatives cOperationAlternatives_0_0 = (Alternatives)cOperationAssignment_0.eContents().get(0);
		private final RuleCall cOperationFoldMaxTranformationParserRuleCall_0_0_0 = (RuleCall)cOperationAlternatives_0_0.eContents().get(0);
		private final RuleCall cOperationFoldSumTranformationParserRuleCall_0_0_1 = (RuleCall)cOperationAlternatives_0_0.eContents().get(1);
		private final RuleCall cOperationFoldAverageTranformationParserRuleCall_0_0_2 = (RuleCall)cOperationAlternatives_0_0.eContents().get(2);
		private final Assignment cGroupByAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cGroupByGroupByParserRuleCall_1_0 = (RuleCall)cGroupByAssignment_1.eContents().get(0);
		
		//FoldTransformation:
		//    operation = (FoldMaxTranformation | FoldSumTranformation | FoldAverageTranformation) groupBy = GroupBy?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//operation = (FoldMaxTranformation | FoldSumTranformation | FoldAverageTranformation) groupBy = GroupBy?
		public Group getGroup() { return cGroup; }
		
		//operation = (FoldMaxTranformation | FoldSumTranformation | FoldAverageTranformation)
		public Assignment getOperationAssignment_0() { return cOperationAssignment_0; }
		
		//(FoldMaxTranformation | FoldSumTranformation | FoldAverageTranformation)
		public Alternatives getOperationAlternatives_0_0() { return cOperationAlternatives_0_0; }
		
		//FoldMaxTranformation
		public RuleCall getOperationFoldMaxTranformationParserRuleCall_0_0_0() { return cOperationFoldMaxTranformationParserRuleCall_0_0_0; }
		
		//FoldSumTranformation
		public RuleCall getOperationFoldSumTranformationParserRuleCall_0_0_1() { return cOperationFoldSumTranformationParserRuleCall_0_0_1; }
		
		//FoldAverageTranformation
		public RuleCall getOperationFoldAverageTranformationParserRuleCall_0_0_2() { return cOperationFoldAverageTranformationParserRuleCall_0_0_2; }
		
		//groupBy = GroupBy?
		public Assignment getGroupByAssignment_1() { return cGroupByAssignment_1; }
		
		//GroupBy
		public RuleCall getGroupByGroupByParserRuleCall_1_0() { return cGroupByGroupByParserRuleCall_1_0; }
	}
	public class AddColumnTransformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.AddColumnTransformation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAddKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cColumnAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cColumnSTRINGTerminalRuleCall_1_0 = (RuleCall)cColumnAssignment_1.eContents().get(0);
		private final Keyword cWithKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValueSTRINGTerminalRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		
		//AddColumnTransformation:
		//    'add' column = STRING 'with' value = STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'add' column = STRING 'with' value = STRING
		public Group getGroup() { return cGroup; }
		
		//'add'
		public Keyword getAddKeyword_0() { return cAddKeyword_0; }
		
		//column = STRING
		public Assignment getColumnAssignment_1() { return cColumnAssignment_1; }
		
		//STRING
		public RuleCall getColumnSTRINGTerminalRuleCall_1_0() { return cColumnSTRINGTerminalRuleCall_1_0; }
		
		//'with'
		public Keyword getWithKeyword_2() { return cWithKeyword_2; }
		
		//value = STRING
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_3_0() { return cValueSTRINGTerminalRuleCall_3_0; }
	}
	public class RemoveColumnTransformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RemoveColumnTransformation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRemoveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cColumnAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cColumnSTRINGTerminalRuleCall_2_0 = (RuleCall)cColumnAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cColumnAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cColumnSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cColumnAssignment_3_1.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cRightSquareBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//RemoveColumnTransformation:
		//    'remove' '[' column += STRING (',' column += STRING)* (',')? ']'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'remove' '[' column += STRING (',' column += STRING)* (',')? ']'
		public Group getGroup() { return cGroup; }
		
		//'remove'
		public Keyword getRemoveKeyword_0() { return cRemoveKeyword_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }
		
		//column += STRING
		public Assignment getColumnAssignment_2() { return cColumnAssignment_2; }
		
		//STRING
		public RuleCall getColumnSTRINGTerminalRuleCall_2_0() { return cColumnSTRINGTerminalRuleCall_2_0; }
		
		//(',' column += STRING)*
		public Group getGroup_3() { return cGroup_3; }
		
		//','
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//column += STRING
		public Assignment getColumnAssignment_3_1() { return cColumnAssignment_3_1; }
		
		//STRING
		public RuleCall getColumnSTRINGTerminalRuleCall_3_1_0() { return cColumnSTRINGTerminalRuleCall_3_1_0; }
		
		//(',')?
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_5() { return cRightSquareBracketKeyword_5; }
	}
	public class RenameColumnTransformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RenameColumnTransformation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRenameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cFromAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cFromSTRINGTerminalRuleCall_1_0 = (RuleCall)cFromAssignment_1.eContents().get(0);
		private final Keyword cToKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cToAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cToSTRINGTerminalRuleCall_3_0 = (RuleCall)cToAssignment_3.eContents().get(0);
		
		//RenameColumnTransformation:
		//    'rename' from = STRING 'to' to = STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'rename' from = STRING 'to' to = STRING
		public Group getGroup() { return cGroup; }
		
		//'rename'
		public Keyword getRenameKeyword_0() { return cRenameKeyword_0; }
		
		//from = STRING
		public Assignment getFromAssignment_1() { return cFromAssignment_1; }
		
		//STRING
		public RuleCall getFromSTRINGTerminalRuleCall_1_0() { return cFromSTRINGTerminalRuleCall_1_0; }
		
		//'to'
		public Keyword getToKeyword_2() { return cToKeyword_2; }
		
		//to = STRING
		public Assignment getToAssignment_3() { return cToAssignment_3; }
		
		//STRING
		public RuleCall getToSTRINGTerminalRuleCall_3_0() { return cToSTRINGTerminalRuleCall_3_0; }
	}
	public class SelectColumnTransformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SelectColumnTransformation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSelectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cColumnAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cColumnSTRINGTerminalRuleCall_2_0 = (RuleCall)cColumnAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cColumnAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cColumnSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cColumnAssignment_3_1.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cRightSquareBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//SelectColumnTransformation:
		//    'select' '[' column += STRING (',' column += STRING)* (',')? ']'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'select' '[' column += STRING (',' column += STRING)* (',')? ']'
		public Group getGroup() { return cGroup; }
		
		//'select'
		public Keyword getSelectKeyword_0() { return cSelectKeyword_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }
		
		//column += STRING
		public Assignment getColumnAssignment_2() { return cColumnAssignment_2; }
		
		//STRING
		public RuleCall getColumnSTRINGTerminalRuleCall_2_0() { return cColumnSTRINGTerminalRuleCall_2_0; }
		
		//(',' column += STRING)*
		public Group getGroup_3() { return cGroup_3; }
		
		//','
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//column += STRING
		public Assignment getColumnAssignment_3_1() { return cColumnAssignment_3_1; }
		
		//STRING
		public RuleCall getColumnSTRINGTerminalRuleCall_3_1_0() { return cColumnSTRINGTerminalRuleCall_3_1_0; }
		
		//(',')?
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_5() { return cRightSquareBracketKeyword_5; }
	}
	public class ColumnTransformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ColumnTransformation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAddColumnTransformationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRemoveColumnTransformationParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRenameColumnTransformationParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cSelectColumnTransformationParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//ColumnTransformation:
		//    (AddColumnTransformation | RemoveColumnTransformation | RenameColumnTransformation | SelectColumnTransformation)
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(AddColumnTransformation | RemoveColumnTransformation | RenameColumnTransformation | SelectColumnTransformation)
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//AddColumnTransformation
		public RuleCall getAddColumnTransformationParserRuleCall_0() { return cAddColumnTransformationParserRuleCall_0; }
		
		//RemoveColumnTransformation
		public RuleCall getRemoveColumnTransformationParserRuleCall_1() { return cRemoveColumnTransformationParserRuleCall_1; }
		
		//RenameColumnTransformation
		public RuleCall getRenameColumnTransformationParserRuleCall_2() { return cRenameColumnTransformationParserRuleCall_2; }
		
		//SelectColumnTransformation
		public RuleCall getSelectColumnTransformationParserRuleCall_3() { return cSelectColumnTransformationParserRuleCall_3; }
	}
	public class TransformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Transformation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPathTransformationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFoldTransformationParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cColumnTransformationParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Transformation:
		//    (PathTransformation | FoldTransformation | ColumnTransformation)
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(PathTransformation | FoldTransformation | ColumnTransformation)
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PathTransformation
		public RuleCall getPathTransformationParserRuleCall_0() { return cPathTransformationParserRuleCall_0; }
		
		//FoldTransformation
		public RuleCall getFoldTransformationParserRuleCall_1() { return cFoldTransformationParserRuleCall_1; }
		
		//ColumnTransformation
		public RuleCall getColumnTransformationParserRuleCall_2() { return cColumnTransformationParserRuleCall_2; }
	}
	public class PipelineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Pipeline");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPipeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cTransformationAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cTransformationTransformationParserRuleCall_4_0_0 = (RuleCall)cTransformationAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cCommaKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cTransformationAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cTransformationTransformationParserRuleCall_4_1_1_0 = (RuleCall)cTransformationAssignment_4_1_1.eContents().get(0);
		private final Keyword cCommaKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Keyword cRightSquareBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Pipeline:
		//    name=ID '=' 'pipe' '['
		//        (transformation += Transformation (',' transformation += Transformation )* (',')?)
		//    ']'';'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID '=' 'pipe' '['
		//    (transformation += Transformation (',' transformation += Transformation )* (',')?)
		//']'';'
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }
		
		//'pipe'
		public Keyword getPipeKeyword_2() { return cPipeKeyword_2; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_3() { return cLeftSquareBracketKeyword_3; }
		
		//(transformation += Transformation (',' transformation += Transformation )* (',')?)
		public Group getGroup_4() { return cGroup_4; }
		
		//transformation += Transformation
		public Assignment getTransformationAssignment_4_0() { return cTransformationAssignment_4_0; }
		
		//Transformation
		public RuleCall getTransformationTransformationParserRuleCall_4_0_0() { return cTransformationTransformationParserRuleCall_4_0_0; }
		
		//(',' transformation += Transformation )*
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//','
		public Keyword getCommaKeyword_4_1_0() { return cCommaKeyword_4_1_0; }
		
		//transformation += Transformation
		public Assignment getTransformationAssignment_4_1_1() { return cTransformationAssignment_4_1_1; }
		
		//Transformation
		public RuleCall getTransformationTransformationParserRuleCall_4_1_1_0() { return cTransformationTransformationParserRuleCall_4_1_1_0; }
		
		//(',')?
		public Keyword getCommaKeyword_4_2() { return cCommaKeyword_4_2; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_5() { return cRightSquareBracketKeyword_5; }
		
		//';'
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
	}
	public class ExportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Export");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTableAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTableIDTerminalRuleCall_1_0 = (RuleCall)cTableAssignment_1.eContents().get(0);
		private final Keyword cToKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPathAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPathSTRINGTerminalRuleCall_3_0 = (RuleCall)cPathAssignment_3.eContents().get(0);
		private final Keyword cAsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cOutputAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cOutputOutputTypeParserRuleCall_5_0 = (RuleCall)cOutputAssignment_5.eContents().get(0);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Export:
		//    'export' table=ID 'to' path = STRING 'as' output = OutputType ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'export' table=ID 'to' path = STRING 'as' output = OutputType ';'
		public Group getGroup() { return cGroup; }
		
		//'export'
		public Keyword getExportKeyword_0() { return cExportKeyword_0; }
		
		//table=ID
		public Assignment getTableAssignment_1() { return cTableAssignment_1; }
		
		//ID
		public RuleCall getTableIDTerminalRuleCall_1_0() { return cTableIDTerminalRuleCall_1_0; }
		
		//'to'
		public Keyword getToKeyword_2() { return cToKeyword_2; }
		
		//path = STRING
		public Assignment getPathAssignment_3() { return cPathAssignment_3; }
		
		//STRING
		public RuleCall getPathSTRINGTerminalRuleCall_3_0() { return cPathSTRINGTerminalRuleCall_3_0; }
		
		//'as'
		public Keyword getAsKeyword_4() { return cAsKeyword_4; }
		
		//output = OutputType
		public Assignment getOutputAssignment_5() { return cOutputAssignment_5; }
		
		//OutputType
		public RuleCall getOutputOutputTypeParserRuleCall_5_0() { return cOutputOutputTypeParserRuleCall_5_0; }
		
		//';'
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
	}
	
	
	private final MyDslElements pMyDsl;
	private final CombinationOperationsElements pCombinationOperations;
	private final TableOperationsElements pTableOperations;
	private final SourceOperationElements pSourceOperation;
	private final TransformationTableOperationElements pTransformationTableOperation;
	private final PipelineTableOperationElements pPipelineTableOperation;
	private final TransformOperationElements pTransformOperation;
	private final TableElements pTable;
	private final XmlTypeElements pXmlType;
	private final JsonTypeElements pJsonType;
	private final YamlTypeElements pYamlType;
	private final CsvTypeElements pCsvType;
	private final AutoTypeElements pAutoType;
	private final InputTypeElements pInputType;
	private final HtmlTypeElements pHtmlType;
	private final OutputTypeElements pOutputType;
	private final MetaDataElements pMetaData;
	private final SourceStoreElements pSourceStore;
	private final SourceCoumnSelectElements pSourceCoumnSelect;
	private final SourceElements pSource;
	private final CanonicalizePathTransformationElements pCanonicalizePathTransformation;
	private final GetPathTransformationElements pGetPathTransformation;
	private final AppendPathTransformationElements pAppendPathTransformation;
	private final PathTransformationElements pPathTransformation;
	private final FoldMaxTranformationElements pFoldMaxTranformation;
	private final FoldAverageTranformationElements pFoldAverageTranformation;
	private final FoldSumTranformationElements pFoldSumTranformation;
	private final GroupByElements pGroupBy;
	private final FoldTransformationElements pFoldTransformation;
	private final AddColumnTransformationElements pAddColumnTransformation;
	private final RemoveColumnTransformationElements pRemoveColumnTransformation;
	private final RenameColumnTransformationElements pRenameColumnTransformation;
	private final SelectColumnTransformationElements pSelectColumnTransformation;
	private final ColumnTransformationElements pColumnTransformation;
	private final TransformationElements pTransformation;
	private final PipelineElements pPipeline;
	private final ExportElements pExport;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pMyDsl = new MyDslElements();
		this.pCombinationOperations = new CombinationOperationsElements();
		this.pTableOperations = new TableOperationsElements();
		this.pSourceOperation = new SourceOperationElements();
		this.pTransformationTableOperation = new TransformationTableOperationElements();
		this.pPipelineTableOperation = new PipelineTableOperationElements();
		this.pTransformOperation = new TransformOperationElements();
		this.pTable = new TableElements();
		this.pXmlType = new XmlTypeElements();
		this.pJsonType = new JsonTypeElements();
		this.pYamlType = new YamlTypeElements();
		this.pCsvType = new CsvTypeElements();
		this.pAutoType = new AutoTypeElements();
		this.pInputType = new InputTypeElements();
		this.pHtmlType = new HtmlTypeElements();
		this.pOutputType = new OutputTypeElements();
		this.pMetaData = new MetaDataElements();
		this.pSourceStore = new SourceStoreElements();
		this.pSourceCoumnSelect = new SourceCoumnSelectElements();
		this.pSource = new SourceElements();
		this.pCanonicalizePathTransformation = new CanonicalizePathTransformationElements();
		this.pGetPathTransformation = new GetPathTransformationElements();
		this.pAppendPathTransformation = new AppendPathTransformationElements();
		this.pPathTransformation = new PathTransformationElements();
		this.pFoldMaxTranformation = new FoldMaxTranformationElements();
		this.pFoldAverageTranformation = new FoldAverageTranformationElements();
		this.pFoldSumTranformation = new FoldSumTranformationElements();
		this.pGroupBy = new GroupByElements();
		this.pFoldTransformation = new FoldTransformationElements();
		this.pAddColumnTransformation = new AddColumnTransformationElements();
		this.pRemoveColumnTransformation = new RemoveColumnTransformationElements();
		this.pRenameColumnTransformation = new RenameColumnTransformationElements();
		this.pSelectColumnTransformation = new SelectColumnTransformationElements();
		this.pColumnTransformation = new ColumnTransformationElements();
		this.pTransformation = new TransformationElements();
		this.pPipeline = new PipelineElements();
		this.pExport = new ExportElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//MyDsl:
	//    pipelines += Pipeline*
	//    sources += Source*
	//    tables += Table*
	//    export += Export*
	//;
	public MyDslElements getMyDslAccess() {
		return pMyDsl;
	}
	
	public ParserRule getMyDslRule() {
		return getMyDslAccess().getRule();
	}
	
	//CombinationOperations:
	//    operation = ('merge' | 'append') type = ("union" | "intersection")?  "["
	//        tableOperation += TableOperations (',' tableOperation+=TableOperations)* (',')?
	//    "]"
	//;
	public CombinationOperationsElements getCombinationOperationsAccess() {
		return pCombinationOperations;
	}
	
	public ParserRule getCombinationOperationsRule() {
		return getCombinationOperationsAccess().getRule();
	}
	
	//TableOperations:
	//    CombinationOperations | TransformOperation    | SourceOperation
	//;
	public TableOperationsElements getTableOperationsAccess() {
		return pTableOperations;
	}
	
	public ParserRule getTableOperationsRule() {
		return getTableOperationsAccess().getRule();
	}
	
	//SourceOperation:
	//    source = ID
	//;
	public SourceOperationElements getSourceOperationAccess() {
		return pSourceOperation;
	}
	
	public ParserRule getSourceOperationRule() {
		return getSourceOperationAccess().getRule();
	}
	
	//TransformationTableOperation:
	//    '('transformation = Transformation')'
	//;
	public TransformationTableOperationElements getTransformationTableOperationAccess() {
		return pTransformationTableOperation;
	}
	
	public ParserRule getTransformationTableOperationRule() {
		return getTransformationTableOperationAccess().getRule();
	}
	
	//PipelineTableOperation:
	//    pipeline = ID
	//;
	public PipelineTableOperationElements getPipelineTableOperationAccess() {
		return pPipelineTableOperation;
	}
	
	public ParserRule getPipelineTableOperationRule() {
		return getPipelineTableOperationAccess().getRule();
	}
	
	//TransformOperation:
	//    source = SourceOperation ('transform' operation += ( TransformationTableOperation | PipelineTableOperation))+
	//;
	public TransformOperationElements getTransformOperationAccess() {
		return pTransformOperation;
	}
	
	public ParserRule getTransformOperationRule() {
		return getTransformOperationAccess().getRule();
	}
	
	//Table:
	//    name=ID '='
	//    operation = TableOperations
	//    ";"
	//;
	public TableElements getTableAccess() {
		return pTable;
	}
	
	public ParserRule getTableRule() {
		return getTableAccess().getRule();
	}
	
	//XmlType:
	//    {XmlType} 'xml'( '{' 'xpath' '=' path = STRING ',' "}" )?
	//;
	public XmlTypeElements getXmlTypeAccess() {
		return pXmlType;
	}
	
	public ParserRule getXmlTypeRule() {
		return getXmlTypeAccess().getRule();
	}
	
	//JsonType:
	//        {JsonType} 'json'( '{' 'jsonpath' '=' path = STRING ',' "}" )?
	//;
	public JsonTypeElements getJsonTypeAccess() {
		return pJsonType;
	}
	
	public ParserRule getJsonTypeRule() {
		return getJsonTypeAccess().getRule();
	}
	
	//YamlType:
	//        {YamlType} 'yaml'
	//;
	public YamlTypeElements getYamlTypeAccess() {
		return pYamlType;
	}
	
	public ParserRule getYamlTypeRule() {
		return getYamlTypeAccess().getRule();
	}
	
	//CsvType:
	//        {CsvType} 'csv'
	//;
	public CsvTypeElements getCsvTypeAccess() {
		return pCsvType;
	}
	
	public ParserRule getCsvTypeRule() {
		return getCsvTypeAccess().getRule();
	}
	
	//AutoType:
	//        {AutoType} 'auto'
	//;
	public AutoTypeElements getAutoTypeAccess() {
		return pAutoType;
	}
	
	public ParserRule getAutoTypeRule() {
		return getAutoTypeAccess().getRule();
	}
	
	//InputType:
	//    JsonType | XmlType | CsvType | YamlType | AutoType
	//;
	public InputTypeElements getInputTypeAccess() {
		return pInputType;
	}
	
	public ParserRule getInputTypeRule() {
		return getInputTypeAccess().getRule();
	}
	
	//HtmlType:
	//    {HtmlType} 'html' ('{''css' '=' cssPath = STRING '}')?
	//;
	public HtmlTypeElements getHtmlTypeAccess() {
		return pHtmlType;
	}
	
	public ParserRule getHtmlTypeRule() {
		return getHtmlTypeAccess().getRule();
	}
	
	//OutputType:
	//    type = (HtmlType | AutoType | CsvType )
	//;
	public OutputTypeElements getOutputTypeAccess() {
		return pOutputType;
	}
	
	public ParserRule getOutputTypeRule() {
		return getOutputTypeAccess().getRule();
	}
	
	//MetaData:
	//    metadata = ('filepath' | 'lastmodified')
	//;
	public MetaDataElements getMetaDataAccess() {
		return pMetaData;
	}
	
	public ParserRule getMetaDataRule() {
		return getMetaDataAccess().getRule();
	}
	
	//SourceStore:
	//    'store' metadata=MetaData 'in' column = STRING
	//;
	public SourceStoreElements getSourceStoreAccess() {
		return pSourceStore;
	}
	
	public ParserRule getSourceStoreRule() {
		return getSourceStoreAccess().getRule();
	}
	
	//SourceCoumnSelect:
	//    'selecting' '[' column += STRING (',' column += STRING)* (',')? ']'
	//;
	public SourceCoumnSelectElements getSourceCoumnSelectAccess() {
		return pSourceCoumnSelect;
	}
	
	public ParserRule getSourceCoumnSelectRule() {
		return getSourceCoumnSelectAccess().getRule();
	}
	
	//Source:
	//    name=ID '=' 'import' (query=STRING)? 'from' filePath=STRING ('as' inputType=InputType)?
	//    store += SourceStore*
	//    select = (SourceCoumnSelect)?
	//    ';'
	//;
	public SourceElements getSourceAccess() {
		return pSource;
	}
	
	public ParserRule getSourceRule() {
		return getSourceAccess().getRule();
	}
	
	//CanonicalizePathTransformation:
	//    {CanonicalizePathTransformation} 'canonicalize' 'path'
	//;
	public CanonicalizePathTransformationElements getCanonicalizePathTransformationAccess() {
		return pCanonicalizePathTransformation;
	}
	
	public ParserRule getCanonicalizePathTransformationRule() {
		return getCanonicalizePathTransformationAccess().getRule();
	}
	
	//GetPathTransformation:
	//    {GetPathTransformation} 'get' 'path' 'name'
	//;
	public GetPathTransformationElements getGetPathTransformationAccess() {
		return pGetPathTransformation;
	}
	
	public ParserRule getGetPathTransformationRule() {
		return getGetPathTransformationAccess().getRule();
	}
	
	//AppendPathTransformation:
	//    'append' 'path' path = STRING
	//;
	public AppendPathTransformationElements getAppendPathTransformationAccess() {
		return pAppendPathTransformation;
	}
	
	public ParserRule getAppendPathTransformationRule() {
		return getAppendPathTransformationAccess().getRule();
	}
	
	//PathTransformation:
	//    'in' column = STRING operation = (AppendPathTransformation | CanonicalizePathTransformation | GetPathTransformation)
	//;
	public PathTransformationElements getPathTransformationAccess() {
		return pPathTransformation;
	}
	
	public ParserRule getPathTransformationRule() {
		return getPathTransformationAccess().getRule();
	}
	
	//FoldMaxTranformation:
	//    'in' column = STRING 'fold' 'max'
	//;
	public FoldMaxTranformationElements getFoldMaxTranformationAccess() {
		return pFoldMaxTranformation;
	}
	
	public ParserRule getFoldMaxTranformationRule() {
		return getFoldMaxTranformationAccess().getRule();
	}
	
	//FoldAverageTranformation:
	//    {FoldAverageTranformation} 'fold' 'avg'
	//;
	public FoldAverageTranformationElements getFoldAverageTranformationAccess() {
		return pFoldAverageTranformation;
	}
	
	public ParserRule getFoldAverageTranformationRule() {
		return getFoldAverageTranformationAccess().getRule();
	}
	
	//FoldSumTranformation:
	//    {FoldSumTranformation} 'fold' 'sum'
	//;
	public FoldSumTranformationElements getFoldSumTranformationAccess() {
		return pFoldSumTranformation;
	}
	
	public ParserRule getFoldSumTranformationRule() {
		return getFoldSumTranformationAccess().getRule();
	}
	
	//GroupBy:
	//    'group' 'by' column = STRING
	//;
	public GroupByElements getGroupByAccess() {
		return pGroupBy;
	}
	
	public ParserRule getGroupByRule() {
		return getGroupByAccess().getRule();
	}
	
	//FoldTransformation:
	//    operation = (FoldMaxTranformation | FoldSumTranformation | FoldAverageTranformation) groupBy = GroupBy?
	//;
	public FoldTransformationElements getFoldTransformationAccess() {
		return pFoldTransformation;
	}
	
	public ParserRule getFoldTransformationRule() {
		return getFoldTransformationAccess().getRule();
	}
	
	//AddColumnTransformation:
	//    'add' column = STRING 'with' value = STRING
	//;
	public AddColumnTransformationElements getAddColumnTransformationAccess() {
		return pAddColumnTransformation;
	}
	
	public ParserRule getAddColumnTransformationRule() {
		return getAddColumnTransformationAccess().getRule();
	}
	
	//RemoveColumnTransformation:
	//    'remove' '[' column += STRING (',' column += STRING)* (',')? ']'
	//;
	public RemoveColumnTransformationElements getRemoveColumnTransformationAccess() {
		return pRemoveColumnTransformation;
	}
	
	public ParserRule getRemoveColumnTransformationRule() {
		return getRemoveColumnTransformationAccess().getRule();
	}
	
	//RenameColumnTransformation:
	//    'rename' from = STRING 'to' to = STRING
	//;
	public RenameColumnTransformationElements getRenameColumnTransformationAccess() {
		return pRenameColumnTransformation;
	}
	
	public ParserRule getRenameColumnTransformationRule() {
		return getRenameColumnTransformationAccess().getRule();
	}
	
	//SelectColumnTransformation:
	//    'select' '[' column += STRING (',' column += STRING)* (',')? ']'
	//;
	public SelectColumnTransformationElements getSelectColumnTransformationAccess() {
		return pSelectColumnTransformation;
	}
	
	public ParserRule getSelectColumnTransformationRule() {
		return getSelectColumnTransformationAccess().getRule();
	}
	
	//ColumnTransformation:
	//    (AddColumnTransformation | RemoveColumnTransformation | RenameColumnTransformation | SelectColumnTransformation)
	//;
	public ColumnTransformationElements getColumnTransformationAccess() {
		return pColumnTransformation;
	}
	
	public ParserRule getColumnTransformationRule() {
		return getColumnTransformationAccess().getRule();
	}
	
	//Transformation:
	//    (PathTransformation | FoldTransformation | ColumnTransformation)
	//;
	public TransformationElements getTransformationAccess() {
		return pTransformation;
	}
	
	public ParserRule getTransformationRule() {
		return getTransformationAccess().getRule();
	}
	
	//Pipeline:
	//    name=ID '=' 'pipe' '['
	//        (transformation += Transformation (',' transformation += Transformation )* (',')?)
	//    ']'';'
	//    ;
	public PipelineElements getPipelineAccess() {
		return pPipeline;
	}
	
	public ParserRule getPipelineRule() {
		return getPipelineAccess().getRule();
	}
	
	//Export:
	//    'export' table=ID 'to' path = STRING 'as' output = OutputType ';'
	//;
	public ExportElements getExportAccess() {
		return pExport;
	}
	
	public ParserRule getExportRule() {
		return getExportAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
