/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pipeline Table Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PipelineTableOperation#getPipeline <em>Pipeline</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPipelineTableOperation()
 * @model
 * @generated
 */
public interface PipelineTableOperation extends EObject
{
  /**
   * Returns the value of the '<em><b>Pipeline</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pipeline</em>' attribute.
   * @see #setPipeline(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPipelineTableOperation_Pipeline()
   * @model
   * @generated
   */
  String getPipeline();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PipelineTableOperation#getPipeline <em>Pipeline</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pipeline</em>' attribute.
   * @see #getPipeline()
   * @generated
   */
  void setPipeline(String value);

} // PipelineTableOperation
