/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Source Coumn Select</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SourceCoumnSelect#getColumn <em>Column</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSourceCoumnSelect()
 * @model
 * @generated
 */
public interface SourceCoumnSelect extends EObject
{
  /**
   * Returns the value of the '<em><b>Column</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column</em>' attribute list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSourceCoumnSelect_Column()
   * @model unique="false"
   * @generated
   */
  EList<String> getColumn();

} // SourceCoumnSelect
