/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transform Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TransformOperation#getSource <em>Source</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TransformOperation#getOperation <em>Operation</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTransformOperation()
 * @model
 * @generated
 */
public interface TransformOperation extends TableOperations
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' containment reference.
   * @see #setSource(SourceOperation)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTransformOperation_Source()
   * @model containment="true"
   * @generated
   */
  SourceOperation getSource();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.TransformOperation#getSource <em>Source</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' containment reference.
   * @see #getSource()
   * @generated
   */
  void setSource(SourceOperation value);

  /**
   * Returns the value of the '<em><b>Operation</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTransformOperation_Operation()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getOperation();

} // TransformOperation
