/*
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class ExternalDslProposalProvider extends AbstractExternalDslProposalProvider {
}
