/**
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.dsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import pt.up.fe.els2023.dsl.Assignment;
import pt.up.fe.els2023.dsl.DslPackage;
import pt.up.fe.els2023.dsl.Export;
import pt.up.fe.els2023.dsl.MyDsl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>My Dsl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link pt.up.fe.els2023.dsl.impl.MyDslImpl#getAssignment <em>Assignment</em>}</li>
 *   <li>{@link pt.up.fe.els2023.dsl.impl.MyDslImpl#getExport <em>Export</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MyDslImpl extends MinimalEObjectImpl.Container implements MyDsl
{
  /**
   * The cached value of the '{@link #getAssignment() <em>Assignment</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAssignment()
   * @generated
   * @ordered
   */
  protected EList<Assignment> assignment;

  /**
   * The cached value of the '{@link #getExport() <em>Export</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExport()
   * @generated
   * @ordered
   */
  protected EList<Export> export;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MyDslImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.MY_DSL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Assignment> getAssignment()
  {
    if (assignment == null)
    {
      assignment = new EObjectContainmentEList<Assignment>(Assignment.class, this, DslPackage.MY_DSL__ASSIGNMENT);
    }
    return assignment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Export> getExport()
  {
    if (export == null)
    {
      export = new EObjectContainmentEList<Export>(Export.class, this, DslPackage.MY_DSL__EXPORT);
    }
    return export;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DslPackage.MY_DSL__ASSIGNMENT:
        return ((InternalEList<?>)getAssignment()).basicRemove(otherEnd, msgs);
      case DslPackage.MY_DSL__EXPORT:
        return ((InternalEList<?>)getExport()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.MY_DSL__ASSIGNMENT:
        return getAssignment();
      case DslPackage.MY_DSL__EXPORT:
        return getExport();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.MY_DSL__ASSIGNMENT:
        getAssignment().clear();
        getAssignment().addAll((Collection<? extends Assignment>)newValue);
        return;
      case DslPackage.MY_DSL__EXPORT:
        getExport().clear();
        getExport().addAll((Collection<? extends Export>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.MY_DSL__ASSIGNMENT:
        getAssignment().clear();
        return;
      case DslPackage.MY_DSL__EXPORT:
        getExport().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.MY_DSL__ASSIGNMENT:
        return assignment != null && !assignment.isEmpty();
      case DslPackage.MY_DSL__EXPORT:
        return export != null && !export.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //MyDslImpl
