/**
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.dsl.impl;

import org.eclipse.emf.ecore.EClass;

import pt.up.fe.els2023.dsl.DslPackage;
import pt.up.fe.els2023.dsl.RowTransformation;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Row Transformation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RowTransformationImpl extends TransformationImpl implements RowTransformation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RowTransformationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.ROW_TRANSFORMATION;
  }

} //RowTransformationImpl
