/**
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.dsl.impl;

import org.eclipse.emf.ecore.EClass;

import pt.up.fe.els2023.dsl.DslPackage;
import pt.up.fe.els2023.dsl.YamlType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Yaml Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class YamlTypeImpl extends InputTypeImpl implements YamlType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected YamlTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.YAML_TYPE;
  }

} //YamlTypeImpl
