/*
 * generated by Xtext 2.32.0
 */
package pt.up.fe.els2023.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ExternalDslUiModule extends AbstractExternalDslUiModule {

	public ExternalDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
