/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MyDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_CombinationOperations_CommaKeyword_5_q;
	protected AbstractElementAlias match_Pipeline_CommaKeyword_4_2_q;
	protected AbstractElementAlias match_RemoveColumnTransformation_CommaKeyword_4_q;
	protected AbstractElementAlias match_SelectColumnTransformation_CommaKeyword_4_q;
	protected AbstractElementAlias match_SourceCoumnSelect_CommaKeyword_4_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MyDslGrammarAccess) access;
		match_CombinationOperations_CommaKeyword_5_q = new TokenAlias(false, true, grammarAccess.getCombinationOperationsAccess().getCommaKeyword_5());
		match_Pipeline_CommaKeyword_4_2_q = new TokenAlias(false, true, grammarAccess.getPipelineAccess().getCommaKeyword_4_2());
		match_RemoveColumnTransformation_CommaKeyword_4_q = new TokenAlias(false, true, grammarAccess.getRemoveColumnTransformationAccess().getCommaKeyword_4());
		match_SelectColumnTransformation_CommaKeyword_4_q = new TokenAlias(false, true, grammarAccess.getSelectColumnTransformationAccess().getCommaKeyword_4());
		match_SourceCoumnSelect_CommaKeyword_4_q = new TokenAlias(false, true, grammarAccess.getSourceCoumnSelectAccess().getCommaKeyword_4());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_CombinationOperations_CommaKeyword_5_q.equals(syntax))
				emit_CombinationOperations_CommaKeyword_5_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Pipeline_CommaKeyword_4_2_q.equals(syntax))
				emit_Pipeline_CommaKeyword_4_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_RemoveColumnTransformation_CommaKeyword_4_q.equals(syntax))
				emit_RemoveColumnTransformation_CommaKeyword_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SelectColumnTransformation_CommaKeyword_4_q.equals(syntax))
				emit_SelectColumnTransformation_CommaKeyword_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SourceCoumnSelect_CommaKeyword_4_q.equals(syntax))
				emit_SourceCoumnSelect_CommaKeyword_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     tableOperation+=TableOperations (ambiguity) ']' (rule end)
	 
	 * </pre>
	 */
	protected void emit_CombinationOperations_CommaKeyword_5_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     transformation+=Transformation (ambiguity) ']' ';' (rule end)
	 
	 * </pre>
	 */
	protected void emit_Pipeline_CommaKeyword_4_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     column+=STRING (ambiguity) ']' (rule end)
	 
	 * </pre>
	 */
	protected void emit_RemoveColumnTransformation_CommaKeyword_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     column+=STRING (ambiguity) ']' (rule end)
	 
	 * </pre>
	 */
	protected void emit_SelectColumnTransformation_CommaKeyword_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     column+=STRING (ambiguity) ']' (rule end)
	 
	 * </pre>
	 */
	protected void emit_SourceCoumnSelect_CommaKeyword_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
